### ISSUE TITLE
we need an ACP

### ISSUE THREAD

**Issue by xzg1102** [dappledger/AnnChain#58]
To set out more new ideas, I think we need a new community for proposal. Like Annchain community Proposal？

**Comment by qwert-2019** [comment]
Agreed,that would be very helpful

**Comment by needkane** [comment]
> To set out more new ideas, I think we need a new community for proposal. Like Annchain community Proposal？

like this "https://github.com/ethereum/EIPs"

**Comment by needkane** [comment]
If you have any great idea,welcome to create issue.
At current stage, we do not consider the ACP

**Comment by xzg1102** [comment]
> > To set out more new ideas, I think we need a new community for proposal. Like Annchain community Proposal？
> 
> like this "https://github.com/ethereum/EIPs"?
nop, we need a format for NEW ISSURE, like 
![image](https://user-images.githubusercontent.com/53218158/70121563-d2ca9f80-16a9-11ea-80ae-f0a57fa75e3e.png)
