### ISSUE TITLE
go test (use go sdk) twice throw error

### ISSUE THREAD

**Issue by needkane** [dappledger/AnnChain#77]
cd ann-go-sdk/example

[kane@localhost example]$ go test
PASS
ok  	github.com/dappledger/ann-go-sdk/example	23.549s
[kane@localhost example]$ go test
--- FAIL: TestKV (6.03s)
    za_test.go:156: 
        	Error Trace:	za_test.go:156
        	Error:      	Expected nil, but got: &errors.errorString{s:"Response error: Error unreflecting result: duplicate key :[107 101 121 49]"}
        	Test:       	TestKV
    za_test.go:169: 
        	Error Trace:	za_test.go:169
        	Error:      	Expected nil, but got: &errors.errorString{s:"Response error: Error unreflecting result: duplicate key :[107 101 121 50]"}
        	Test:       	TestKV
    za_test.go:182: 
        	Error Trace:	za_test.go:182
        	Error:      	Expected nil, but got: &errors.errorString{s:"Response error: Error unreflecting result: duplicate key :[107 101 121 51]"}
        	Test:       	TestKV
    za_test.go:204: key2 value2
    za_test.go:204: key3 value3
FAIL
exit status 1
FAIL	github.com/dappledger/ann-go-sdk/example	20.851s

**Comment by wickyyang** [comment]
Error has responded "Response error: Error unreflecting result: duplicate key :[107 101 121 51]"
